version: '3.9'

services:
  database:
    image: postgres:15
    container_name:
      postgres

    restart: on-failure

    env_file:
      - .env

    ports:
      - 5432:5432

    volumes:
      - /var/lib/db:/var/lib/postgresql/data

  blog:
    build:
      context: .
      dockerfile: Dockerfile

    container_name:
      blog

    restart: on-failure

    env_file:
      - .env
    # environment:
    #   ENVIRONMENT: DOCKER-DEVELOPMENT

    ports:
      - 8000:8000

    depends_on:
      - database
