version: '3.9'

services:
  database:
    image: postgres:15
    restart: always
    env_file:
      - .env

  blog-backend:
    build: .
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - database
    env_file:
      - .env


#     volumes:
#       - /var/lib/db:/var/lib/postgresql/data

# volumes:
#   db:
#     external: true
